# Generated by Django 4.1.4 on 2023-05-02 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttle', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='throttlemodel',
            options={'ordering': ['-id'], 'permissions': (('view_task', 'View task'),), 'verbose_name': 'bomiot Throttle', 'verbose_name_plural': 'bomiot Throttle'},
        ),
    ]
