# Generated by Django 4.1.4 on 2023-05-02 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttle', '0002_alter_throttlemodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='throttlemodel',
            options={'ordering': ['-id'], 'permissions': (), 'verbose_name': 'bomiot Throttle', 'verbose_name_plural': 'bomiot Throttle'},
        ),
    ]
