# Generated by Django 4.1.4 on 2023-05-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttle', '0003_alter_throttlemodel_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='throttlemodel',
            table='bomiot_throttle',
        ),
    ]
