# Generated by Django 4.1.4 on 2023-05-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('throttle', '0004_alter_throttlemodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='throttlemodel',
            name='create_time',
        ),
        migrations.RemoveField(
            model_name='throttlemodel',
            name='is_delete',
        ),
        migrations.RemoveField(
            model_name='throttlemodel',
            name='update_time',
        ),
    ]
