# Generated by Django 4.1.4 on 2023-05-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_is_delete'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id'], 'permissions': (), 'verbose_name': 'bomiot User', 'verbose_name_plural': 'bomiot User'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='bomiot_user',
        ),
    ]
